### ISSUE TITLE
UniqueIndexChecker does not infer association key from association

### ISSUE THREAD

**Issue by christos** [djezzzl/database_consistency#140]
In the following code, Rails can correctly infer that `validates :category, uniqueness: { scope: :post }` refers to the unique `index_categorisations_on_category_id_and_post_id` but the `UniqueIndexChecker` doesn't do that inference correctly.

```ruby
class Categorisation < ActiveRecord::Base 
  belongs_to :category
  belongs_to :post

  # Rails correctly infers `category_id` and `post_id` here but UniqueIndexChecker doesn't and so fails
  validates :category, uniqueness: { scope: :post }
end
```

I tried to follow the Rails source code for the `UniquenessValidator` to see how `UniqueIndexChecker` can be adapted to infer the key too, but I got stuck. Any pointers?

**Comment by djezzzl** [comment]
Hi @christos,

Thank you for letting me know! Indeed, I see we have this issue. I'll fix this today and share with you the new released version.

**Comment by djezzzl** [comment]
> Any pointers?

It happens here in ActiveRecord:

```
def build_relation(klass, attribute, value)
        relation = klass.unscoped
        comparison = relation.bind_attribute(attribute, value) do |attr, bind|
          return relation.none! if bind.unboundable?
```

So they check if it's an association first:

```
def bind_attribute(name, value) # :nodoc:
      if reflection = klass._reflect_on_association(name)
        name = reflection.foreign_key
        value = value.read_attribute(reflection.klass.primary_key) unless value.nil?
      end

      attr = table[name]
      bind = predicate_builder.build_bind_attribute(attr.name, value)
      yield attr, bind
    end
```

**Comment by djezzzl** [comment]
Fixed here: https://github.com/djezzzl/database_consistency/pull/141.

Released in 1.3.2. Please try it and let me know if it works fine for you. Feel free to reopen the issue!

BTW, feel free to share any ideas for the gem that could be valuable for you and your projects. Have a great day!

**Comment by christos** [comment]
@djezzzl Working great now. Thanks for the quick fix!

> BTW, feel free to share any ideas for the gem that could be valuable for you and your projects.

Will do!

**Comment by djezzzl** [comment]
Thank you @christos,  for quickly validating this! Have a great time!
