### ISSUE TITLE
`EnumTypeChecker` is complaining about `enum` column

### ISSUE THREAD

**Issue by toydestroyer** [djezzzl/database_consistency#160]
Hey there! Me again.

I've identified an issue with the new `EnumTypeChecker`. We store our enums in `enum` type columns in postgres. We are using [this gem](https://github.com/bibendi/activerecord-postgres_enum) to do so, but it is also available [in Rails 7 natively](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html#method-i-create_enum).

Anyway, `EnumTypeChecker` doesn't like it. But it should be okay and even preferable!

I would actually love to have a checker that complains when you try to store ActiveRecord enums in non-enum columns.

**Comment by djezzzl** [comment]
Hi @toydestroyer , 

Thank you for sharing this! Indeed I agree this should be improved! 

I will fix it ASAP.

**Comment by djezzzl** [comment]
The issue was released in 1.5.1. Please try it out and let me know if it still stays.

**Comment by toydestroyer** [comment]
Verified 👍

Thanks for your amazing work @djezzzl! I hope I'll be able to finally contribute at some point 😂

> I would actually love to have a checker that complains when you try to store ActiveRecord enums in non-enum columns.

What do you think about this? Shall I open another issue for discussion?

**Comment by djezzzl** [comment]
Hey @toydestroyer,

> I hope I'll be able to finally contribute at some point 😂

You have already contributed a lot! Please keep it going! 

> What do you think about this? Shall I open another issue for discussion?

I like the idea but we should have sound reasoning for suggesting this. This is an excellent opportunity for comprehensive research. For example, do we save any space on a disk with enums? Or is the querying/filtering/sorting/indexing any faster?

In case we see it has more benefits than disadvantages, I'm all up to have this checker. Would you like to research it and share it?
