### ISSUE TITLE
`ColumnPresenceChecker` and polymorphic association

### ISSUE THREAD

**Issue by toydestroyer** [djezzzl/database_consistency#163]
Hi hi!

Looks like I found another bug.

Let's say you have a model with a polymorphic association and a presence validation:
```ruby
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  validates :imageable, presence: true
end
```

And if you try to autofix this association — only `imageable_id` column would be made non-nullable. But I think it should be both `*_id` and `*_type` columns should be changed.

**Comment by djezzzl** [comment]
Hi @toydestroyer ,

Thank you again! Could you please try version 1.5.3 and let me know if that was fixed?
