### ISSUE TITLE
`ColumnPresenceChecker`, `belongs_to `associations, and `optional`, `required` options

### ISSUE THREAD

**Issue by toydestroyer** [djezzzl/database_consistency#164]
👋

`belongs_to` association might have `optional: false` or `required: true` option.

I'm not really sure that it does exactly the same thing as the presence validator, but I guess DatabaseConsistency should report that such association missing a `NOT NULL` constraint.

What do you think?

P. S. [`belongs_to` associations are required by default from Rails 5](https://www.bigbinary.com/blog/rails-5-makes-belong-to-association-required-by-default), but it is still possible to override this behavior with `ActiveRecord::Base.belongs_to_required_by_default`

**Comment by djezzzl** [comment]
I agree with you and it seems it works fine for me. 

I've checked rails6-example folder and I see this:
```
ColumnPresenceChecker fail User country association foreign key column should be required in the database
```

I also see this spec:

```
context 'when null constraint is missing for the association key' do
    before do
      define_database_with_entity { |table| table.string :user_id }
    end

    let(:attribute) { :user }

    context 'when `belongs_to` is required' do
      let(:klass) { define_class { |klass| klass.belongs_to :user, **required } }

      specify do
        expect(checker.report).to have_attributes(
          checker_name: 'ColumnPresenceChecker',
          table_or_model_name: klass.name,
          column_or_attribute_name: 'user',
          status: :fail,
          error_message: nil,
          error_slug: :association_missing_null_constraint
        )
      end
    end

    context 'when `belongs_to` is optional' do
      let(:klass) { define_class { |klass| klass.belongs_to :user, **optional } }

      specify do
        expect(checker.report).to be_nil
      end
    end
  end
```

Please let me know if it doesn't work for you, I would gladly fix it. Feel free to reopen an issue.

**Comment by toydestroyer** [comment]
I could swear it wasn't working yesterday on my machine 😂
Sorry about this! I will be more careful next time before opening an issue.

**Comment by djezzzl** [comment]
No need to apologize! Thank you for keeping a sharp eye on any issues!
