### ISSUE TITLE
database_consistency -f generates duplicate migrations

### ISSUE THREAD

**Issue by zapxcero** [djezzzl/database_consistency#175]
Steps to reproduce.

1. bundle exec database_consistency -f
2. Migrations are created.
3. Run step 1 again without migrating db
4. Duplicates with the same name are created.

Idk if this should be an issue or feature request.

**Comment by djezzzl** [comment]
Hi @zapxcero ,

Thank you for letting us know! I will fix it as soon as possible.

**Comment by djezzzl** [comment]
Hi @zapxcero,

It was fixed here: https://github.com/djezzzl/database_consistency/pull/177.

**Comment by djezzzl** [comment]
The fix was released in 1.7.3. Please try it out and let me know if that helped. Thank you again, and have a great day!
