### ISSUE TITLE
Failure log when having functional indexes

### ISSUE THREAD

**Issue by palkan** [djezzzl/database_consistency#18]
`bundle exec database_consistency` generates a failure log (just a file named `database_consistency_<date>_<and>_<time>`) containing the following line:

```
/bundle/gems/database_consistency-0.6.5/lib/database_consistency/checkers/missing_unique_index_checker.rb:36:in `block in unique_index': [1mundefined method `sort' for "lower((email)::text)":String ([1;4mNoMethodError[m[1m)[m
```

**Comment by djezzzl** [comment]
Yes, this is a correct behaviour for errors implemented by `DatabaseConsistency::RescueError`. Thank you for creating an issue, I'm working on supporting `case_sensetive: false`.

**Comment by djezzzl** [comment]
Fixed https://github.com/djezzzl/database_consistency/pull/19. Try 0.6.6 version.

**Comment by palkan** [comment]
Thanks!
