### ISSUE TITLE
ForeignKeyCascadeChecker default mapping

### ISSUE THREAD

**Issue by pyromaniac** [djezzzl/database_consistency#186]
Hey @djezzzl I believe that the mapping here https://github.com/djezzzl/database_consistency/blob/a2be80b47fc9cc165c302cf2da60a03a5dfd473d/lib/database_consistency/checkers/association_checkers/foreign_key_cascade_checker.rb#L20-L21 is not entirely correct.
Accordingly to https://stackoverflow.com/questions/60043008/when-to-use-nothing-or-restrict-for-on-delete-with-ecto the default NO ACTION value also raises an error, it is just deferred. But for this purpose it would be perfect to have something like:

```ruby
      OPTION_TO_CASCADE = {
        delete: :cascade,
        delete_all: :cascade,
        nullify: :nullify,
        restrict_with_exception: [nil, :restrict],
        restrict_with_error: [nil, :restrict]
      }.freeze
```

WDYT?

**Comment by djezzzl** [comment]
Hi @pyromaniac,

Yes, it seems you're correct. Thank you for sharing this! Would you like to make a PR for that?

**Comment by pyromaniac** [comment]
Yes, will do soon
