### ISSUE TITLE
Conflict between CaseSensitiveUniqueValidationChecker and UniqueIndexChecker

### ISSUE THREAD

**Issue by mwesigwa** [djezzzl/database_consistency#227]
Thank you for the great work on this gem. It showed a lot of loopholes in our DB schema! 🎉 However I run into an unsolvable situation with Postgres citext columns where 2 checkers give conflicting instructions and result in a seemingly unsolvable scenario.

### Scenario Description

Given a simple table `users` and corresponding ActiveRecord model
```
id -> int
name -> citext
index on lower(name)
```

### Scenario 1
When you add the disable case_sensitivity on your validator:
```
validates :name, :slug, uniqueness: {case_sensitive: false}
```
The result is `CaseSensitiveUniqueValidationChecker` complains with `fail User name has case insensitive type and doesn't require case_sensitive: false option` but `UniqueIndexChecker` is perfectly happy

### Scenario 2
When you do not add disable case_sensitivity on your validator:
```
validates :name, :slug, uniqueness: true
```
The result is `UniqueIndexChecker` complains with `fail Company index_companies_on_LOWER_slug index is unique in the database but do not have uniqueness validator` but `CaseSensitiveUniqueValidationChecker` is perfectly happy

This is a catch 22. Reading the source, it seems like this might boil down to some modification of the [wrapped_attribute_name](https://github.com/djezzzl/database_consistency/blob/master/lib/database_consistency/helper.rb#L119)
method, or somewhere higher in the method like [here](https://github.com/djezzzl/database_consistency/blob/master/lib/database_consistency/checkers/validator_checkers/missing_unique_index_checker.rb#L51) where we do the comparison.

Willing to help craft a solution the issue is deemed worth fixing. Please let me know and thanks again for your great work!

**Comment by ql** [comment]
@mwesigwa Hello! This seems to be a bit of a corner-case. First of all, combination of `citext` field and `LOWER(name)` index seems to be wrong to me  - I see no case when such combination would make sense. 

Then (as far as I know) it's not possible to automatically create `LOWER(name)` index, it would require using SQL statements in index definition. That means to me that somebody deliberately created this conundrum being aware of consequences.

Given these considerations I think that current behaviour of checkers is viable - the configuration is broken, so checkers show that something is off, and it's up to developer to decide if the field's type has to be changed to `string` or index type should become `name`, without additional transformation. In my opinion there are no case when checkers should pass such a schema.

What do you think?

**Comment by mwesigwa** [comment]
@ql. Thank you for walking through this with me. You explained it wonderfully. Turns out I'd done this to match `shoulda-matchers` case-insensitive check, but after unwinding the changes, that seems to pass as well. Please feel free to close the issue as resolved.
