### ISSUE TITLE
Unexpected exit codes

### ISSUE THREAD

**Issue by stephendolan** [djezzzl/database_consistency#23]
Hi there,

First of all, thanks so much for this gem. It's going to be incredibly useful to our team for maintaining best practices. To that effect, I'm implementing it into our CI/CD pipelines, and noticed the following:

If there are no errors, the exit status is a failure:
```bash
> bundle exec database_consistency

> echo $?                                             
1
```

If there are failures, the exit status is a failure:
```bash
> bundle exec database_consistency
fail User lunch_option_attendances associated model should have proper index in the database

> echo $?
1
```

Is there any way to either add a flag or default behavior to give a success exit code if no errors are found, and otherwise give a failing exit code?

Currently, my workaround is to negate a `grep` for the word `fail`. It works, but isn't super elegant:
`! bundle exec database_consistency | grep fail`

**Comment by djezzzl** [comment]
Hi @stephendolan, 

Thank you for your kind words! 

Let me investigate your problem, I'll fix it ASAP and will back to you.

**Comment by djezzzl** [comment]
Hey @stephendolan, could you please try latest version (0.6.9)? The issue was resolved by this PR: https://github.com/djezzzl/database_consistency/pull/24/files#diff-38614b946b60ae29c3eb74cd1a9a8887R41.

**Comment by stephendolan** [comment]
That works great! Thank you very much, @djezzzl !
