### ISSUE TITLE
Issue with database not enabled AND it does not exist

### ISSUE THREAD

**Issue by chaadow** [djezzzl/database_consistency#233]
<details>
<summary>Error file</summary>
Peek a boo!

<===begin===>
Metadata:
Stack trace:
/Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:63:in `rescue in new_client': `[1mWe could not find your database: hoggo_care_data_development. Available database configurations can be found in config/database.yml. ([1;4mActiveRecord::NoDatabaseError[m[1m)[m`
[1mTo resolve this error:[m

[1m- Did you not create the database, or did you delete it? To create the database, run:[m

[1m    bin/rails db:create[m

[1m- Has the database name changed? Verify that config/database.yml contains the correct database name.[m

	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:57:in `new_client'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:926:in `connect'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:938:in `reconnect'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:662:in `block in reconnect!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:661:in `reconnect!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:763:in `block in verify!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:754:in `verify!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:771:in `connect!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:977:in `block in with_raw_connection'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb:128:in `quote_string'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:76:in `quote'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb:122:in `quote'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:1097:in `quoted_scope'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:1074:in `data_source_sql'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:60:in `table_exists?'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:42:in `block in models'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:40:in `select'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:40:in `models'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:56:in `parent_models'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/columns_processor.rb:19:in `check'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:31:in `reports'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:16:in `block in reports'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:15:in `each'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:15:in `flat_map'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:15:in `reports'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency.rb:112:in `run'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/bin/database_consistency:78:in `<top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/database_consistency:25:in `load'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/database_consistency:25:in `<top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:455:in `exec'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:28:in `block in <top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:20:in `<top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/bundle:25:in `load'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/bundle:25:in `<main>'
/Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.7/lib/pg/connection.rb:709:in `async_connect_or_reset': [1mconnection to server at "::1", port 5432 failed: FATAL:  database "hoggo_care_data_development" does not exist ([1;4mPG::ConnectionBad[m[1m)[m
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.7/lib/pg/connection.rb:841:in `connect_to_hosts'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.7/lib/pg/connection.rb:772:in `new'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/pg-1.5.7/lib/pg.rb:63:in `connect'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:58:in `new_client'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:926:in `connect'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:938:in `reconnect'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:662:in `block in reconnect!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:661:in `reconnect!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:763:in `block in verify!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:754:in `verify!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:771:in `connect!'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:977:in `block in with_raw_connection'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activesupport/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb:128:in `quote_string'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:76:in `quote'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb:122:in `quote'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:1097:in `quoted_scope'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:1074:in `data_source_sql'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/rails-c3d8dc47257a/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:60:in `table_exists?'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:42:in `block in models'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:40:in `select'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:40:in `models'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/helper.rb:56:in `parent_models'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/columns_processor.rb:19:in `check'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:31:in `reports'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:16:in `block in reports'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:15:in `each'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:15:in `flat_map'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency/processors/base_processor.rb:15:in `reports'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/lib/database_consistency.rb:112:in `run'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/database_consistency-1.7.24/bin/database_consistency:78:in `<top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/database_consistency:25:in `load'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/database_consistency:25:in `<top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:455:in `exec'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:28:in `block in <top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/chedli/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.15/exe/bundle:20:in `<top (required)>'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/bundle:25:in `load'
	from /Users/chedli/.rbenv/versions/3.3.4/bin/bundle:25:in `<main>'
<===end===>
</details>

Right now whenever I onboard a new developer in my team, the workaround is to do `createdb my_disabled_db` 

However what's ideal is that all models that are disabled or part of a database that is disabled should just be ignored (which they are when the database is "created"

To reproduce : 
- in .database_consistency.yml config :  
 ```yml
  - DatabaseConsistencyDatabases:
      my_disabled_db:
        enabled: false
```

When we run `bundle exec database_consistency` AND `my_disabled_db` does not exist ==> the command crashes with the error log above.
However when I simply create the database with `createdb my_disabled_db` and the database is empty with no tables, it works.

I've worked on a fix and I will submit a PR shortly

**Comment by djezzzl** [comment]
Thank you for noticing it and fixing it! https://github.com/djezzzl/database_consistency/pull/234
