### ISSUE TITLE
LengthConstraintChecker with Integer and BigInt

### ISSUE THREAD

**Issue by 6temes** [djezzzl/database_consistency#28]
I am using Rails with Postgres and I get this errors for all my models:

```
fail MyModel id column has limit in the database but do not have length validator
fail MyModel my_other_model_id column has limit in the database but do not have length validator
fail MyOtherModel things_count column has limit in the database but do not have length validator
```

In the schema, all those values are default `:bigint(8)` and `:integer`. Is it a good practice to add a validator for, for instance, the `ids`? I think it isn't.

By the way, for what I've seen, with Postgres, ActiveRecord defines the `sql_type_metadata` of BigInt as `#<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x00007fe001502ad8 @limit=8, @precision=nil, @scale=nil, @sql_type="bigint", @type=:integer>`

So this check:

https://github.com/djezzzl/database_consistency/blob/bb4e57b3244847774307b544714f7018218ee41b/lib/database_consistency/checkers/column_checkers/length_constraint_checker.rb#L23

Does not seem to work.

Thanks!

**Comment by djezzzl** [comment]
Hi @6temes, thank you for pointing this out!

I also don't think it's right to check IDs. I'll fix it today and let you know 👍

**Comment by djezzzl** [comment]
Hey, should be fixed in this PR: https://github.com/djezzzl/database_consistency/pull/29. Could you try latest version, please? Version: `0.7.1`. If it doesn't help please let me know.

**Comment by 6temes** [comment]
Works great. Thank you!
