### ISSUE TITLE
Custom validatios

### ISSUE THREAD

**Issue by stoivo** [djezzzl/database_consistency#32]
Hi I install the tool today and founy 986 failures. Maybe some are false positive. Any way very nice tool. Found it from Evil Marintins notes. https://github.com/evilmartians/terraforming-rails

When I first ran it it failed. I open the gem to peak in.
We have a custom validator witch does not have an attribute.

```ruby 
# app/models/invoice_transcription.rb
class InvoiceTranscription < ApplicationRecord
  validates_with CustomerCarAndCarRegistrationValidator
end

# app/validators/customer_car_and_car_registration_validator.rb
class CustomerCarAndCarRegistrationValidator < ActiveModel::Validator
  def validate record
    return if record.customer_car_id.blank? == record.customer_car_registration_id.blank?
    record.errors.add :customer_car_id, message: I18n.t(:car_id_and_car_registration_id_required)
  end
end
```

I patched validators_processor.rb little and then it worked. I dont think this is the cleanes patch we could come up with.

```ruby
# lib/database_consistency/processors/validators_processor.rb

# from
  validator.attributes.flat_map do |attribute|

# to
  (validator.attributes rescue []).flat_map do |attribute|
```

Can we fix this?

**Comment by djezzzl** [comment]
Hey, thank you for pointing this out! 

Yeah, I'll fix it ASAP and get back to you 👍 

I'm glad that the tool helps you 👍 

BTW, if you have any ideas or improvements, feel free to open an issue/PR.

**Comment by djezzzl** [comment]
The issue was fixed. Please update to latest version: `0.7.3`.

**Comment by stoivo** [comment]
Works like a charm. Thanks you very much for the tool and the amazingly quick fix.

**Comment by djezzzl** [comment]
Great 👍 Thank you too!
