### ISSUE TITLE
Doesn't appear to work? False negatives.

### ISSUE THREAD

**Issue by nozpheratu** [djezzzl/database_consistency#36]
It appears that all the validators are failing, even a very simple `null: false` column in my database is appearing as nullable and getting flagged by database_consistency.

I am using Rails v6.0.0.rc2 if it matters, along with the mysql2 v0.4.4 gem.

Here is an example:

Migration:
```
class DeviseTokenAuthCreateUsers < ActiveRecord::Migration[6.0]
  def change
    create_table(:users, id: false) do |t|
      t.string :id, limit: 36, primary_key: true, null: false
      ## Required
      t.string :uid, null: false, default: ''
      ....
   end
end 
```

Schema:
```
  create_table "users", id: :string, limit: 36, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "uid", default: "", null: false
   ...
  end
```

And when I run the database consistency rake task, I get this:
> fail User uid column is required but there is possible null value insert

**Comment by djezzzl** [comment]
Hi, could you show how do you define your `User` class?

Basically, `column is required but there is possible null value insert` the error means, you have `null` constraint on the database level, but you don't have a `validate :uid, presence: true` on your model. So there is a chance you'll try to insert `null` value and get a database error as response. 

With proper validation you'll avoid redundant insert query and get validation error instead. 

So, if you don't have presence validator and you don't want it to be, just disable the check for this column. You can see [here](https://github.com/djezzzl/database_consistency/blob/master/rails-example/.database_consistency.yml) how to do it.

**Comment by nozpheratu** [comment]
Here's the model, as you can see I'm using devise:

```
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable

  include DeviseTokenAuth::Concerns::User

  # https://github.com/lynndylanhurley/devise_token_auth/issues/1013#issuecomment-429427773
  def will_save_change_to_email?
    super
  end

  def email_changed?
    super
  end
end
```

The validatable module provides ass the necessary validations, but just to be safe, I also tried adding a:

```
validates :email, presence: true
```

But I met the same error.

**Comment by djezzzl** [comment]
Hey, `email` field has nothing to do with `uid` field. 
`fail User uid column is required but there is possible null value insert`. 

Could you please provide more specific details (complete output for few models, schema for these models and the definition of those few models)? Because gem should work properly in that situation. It will be also cool if you give an example project which I could run and see the issue you're talking about.

**Comment by djezzzl** [comment]
Hey, please share the information I asked above. Until that, I'll close an issue because it seems for me that you handled a situation.

**Comment by nozpheratu** [comment]
I realize those are two different columns. That was just a confusing example on my part, I'm also getting the following warning more relevant to my example (despite the validation):

```
fail User email column is required but there is possible null value insert
```

My only model is the above User model. Here's the full schema:

```
ActiveRecord::Schema.define(version: 2019_08_12_215415) do
  create_table "users", id: :string, limit: 36, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "provider", default: "email", null: false
    t.string "uid", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.boolean "allow_password_change", default: false
    t.datetime "remember_created_at"
    t.string "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.string "unconfirmed_email"
    t.integer "failed_attempts", default: 0, null: false
    t.string "unlock_token"
    t.datetime "locked_at"
    t.string "email", null: false
    t.text "tokens"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["confirmation_token"], name: "index_users_on_confirmation_token", unique: true
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
    t.index ["uid", "provider"], name: "index_users_on_uid_and_provider", unique: true
    t.index ["unlock_token"], name: "index_users_on_unlock_token", unique: true
  end
end
```

**Comment by djezzzl** [comment]
Oh, sorry, I just understood what is a problem:
`fail User uid column is required but there is possible null value insert.`

So, `devise` adds a `presence` validation on `email` field but with some condition (`if` or `else`) statement. So there is still some chance to try to insert `null` value. 

If you try to play with your own `validates :email, presence: true`, i.e. put it before anything, in the very top of model definition, or in the very bottom, most likely in one of cases your error will disappear.

But to get rid of this message, I'd suggest you just to ignore it. There is a [way](https://github.com/djezzzl/database_consistency/blob/master/rails-example/.database_consistency.yml) to do so.

For you case, it should be like:
```
User:
  email: 
    NullConstraintChecker:
      enabled: false # we are sure we have validation
```
