### ISSUE TITLE
Support for official Rails 6 Release

### ISSUE THREAD

**Issue by stephendolan** [djezzzl/database_consistency#37]
Thanks so much for this wonderful gem.

It looks like this isn't compatible with Rails 6 official that was released yesterday:
`spec.add_dependency 'activerecord', '>= 3.2', '< 6'`

Is this intentional? I've been running it with the RC1/RC2 releases without issue.

**Comment by djezzzl** [comment]
Hi @stephendolan, thank you for kind words! 

I'll fix this today 👍

**Comment by djezzzl** [comment]
I just released a new version `0.7.4`. It should support Rails 6. Try it and if it doesn't help let me know, please.  Have a great time 👍
