### ISSUE TITLE
Confused by error message.

### ISSUE THREAD

**Issue by thomasdziedzic** [djezzzl/database_consistency#39]
I have the following model:

```ruby
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :email, presence: true, length: { maximum: 255 }
  ...
end
```

and the following sql column:

```
	email varchar(255) default '' not null,
```

When I run the gem, I get the error:

```
fail User email column is required but there is possible null value insert
```

I'm confused because I have presence: true on the model and not null in the database, so it shouldn't be possible for a null value insert.

**Comment by djezzzl** [comment]
Hey, thank you for pointing this out 👍 

Could you please share `User._validators[:email]`? 

I think the error can be because of the way we check validators. I think you have few `presence` validators on `email` column and some of them have `if`/`unless` conditions. 

The fix to "group" similar validators can take some time and before I'd like to be sure that we should do that or not.

**Comment by thomasdziedzic** [comment]
Here is the output:

```
irb(main):001:0> User._validators[:email]
=> [#<ActiveRecord::Validations::PresenceValidator:0x00007f54005bc880 @attributes=[:email], @options={:if=>:email_required?}>, #<ActiveRecord::Validations::UniquenessValidator:0x00007f54005bc0b0 @attributes=[:email], @options={:allow_blank=>true, :case_sensitive=>true, :if=>:will_save_change_to_email?}, @klass=User (call 'User.connection' to establish a connection)>, #<ActiveModel::Validations::FormatValidator:0x00007f54005ce490 @attributes=[:email], @options={:with=>/\A[^@\s]+@[^@\s]+\z/, :allow_blank=>true, :if=>:will_save_change_to_email?}>, #<ActiveRecord::Validations::PresenceValidator:0x00007f54005c7708 @attributes=[:email], @options={}>, #<ActiveRecord::Validations::LengthValidator:0x00007f54005c64e8 @attributes=[:email], @options={:maximum=>255}>]
```

**Comment by djezzzl** [comment]
So I was right, you have many presence validators and some of them have conditions, so when we iterate through all validators and check specific one, we see it has conditions, so we decide to show a warning. 

As quik fix I'm suggesting you to disable this check for `email` column of your model using configurations. In the meaning time, I'll try to fix it in the gem next week. It will require a lot of effort to re-architect some stuff. 

I keep you posted. Thank you 👍

**Comment by thomasdziedzic** [comment]
Thank you for your time!

**Comment by djezzzl** [comment]
Hey, sorry for making you wait so long! I hope you still use the gem. 
[This PR](https://github.com/djezzzl/database_consistency/pull/43) should fix your problem, could you please check and share results with me? (It was already released with latest version`.0.7.6`) Thank you! Have a great time!

Feel free to reopen an issue if still stays.
