### ISSUE TITLE
Checks has_many, has_and_belongs_to_many wrongly

### ISSUE THREAD

**Issue by sinankeskin** [djezzzl/database_consistency#42]
First of all thank you for the amazing tool.

I have a model like;

```ruby
class Listing < ApplicationRecord
  has_many :listing_items
  has_many :locations
end
```

and also I have a model,
```ruby
class FinanceInfo < ApplicationRecord
  has_and_belongs_to_many :payment_methods
end
```

When I check it shows;

```log
fail Listing listing_items model should have proper foreign key in the database
fail Listing locations model should have proper foreign key in the database
fail FinanceInfo payment_methods model should have proper foreign key in the database 
```

In my case ListingItem and Location models have FKs for Listing and join table for PaymentMethod also has a FK for FinanceInfo.

I believe this checks should be working only belongs_to relationships but it shows for has_many and has_and_belongs_to_many relationships also.

Thank you.

**Comment by djezzzl** [comment]
Hi @sinankeskin, 

I'm glad that the tool helps you! 

> I believe this checks should be working only belongs_to relationships but it shows for has_many and has_and_belongs_to_many relationships also.

I'd disagree here with you, because even your connection is optional, meaning there can be 0 `listing_items` or `locations`, it still worth and possible to have foreign key constaint in the database. 

If one day, by accident, you will remove `Listing` item which has some `Locations`, with FK it won't happen until you clean those `locations`. Without FK, you will break your data consistency. 

Sorry for such slow response. I'll close an issue until we agree it's still an issue. 

Have a great day 👍

**Comment by sinankeskin** [comment]
> I believe this checks should be working only belongs_to relationships but it shows for has_many and has_and_belongs_to_many relationships also.

What I mean by that is, in my scenario you should check the listing item model for FKs not the listing model.

And as I wrote before I have FKs in my database for listing item and I'm still seeing the `fail Listing listing_items model should have proper foreign key in the database` error.

[Here](https://i.ibb.co/Jt9knDM/fk.png) is the screen shot of dbeaver.

Thank you.

**Comment by djezzzl** [comment]
Hey,

Understood. May I ask you to share few things, please, so I can reproduce and understand what's happening? 

I need: 
- Schema of Listing model table (including FKs)
- Schema of ListingItem model table (including FKs)
- Definition of associations in both models

Unfortunately, I can barely see anything on your previous screenshot, please provide a data with better quality. 

Thank you!

**Comment by sinankeskin** [comment]
Hi.

I can't show you my table schema but I've created a brand new rails application [repo](https://github.com/sinankeskin/database_consistency_test) and moved my 2 tables to in it (of course, by simplifying it).

I could reproduce the see same message.

It's using postgresql as a database and after bundling you should use rails db:schema:load.

Thank you.

**Comment by djezzzl** [comment]
Hey, thank you for your example. I've found the problem and you're precisely right. I'm working on fix now.

**Comment by djezzzl** [comment]
Hi, the fix was just released: 0.7.8. Could you please try it out and say if it helps? 

Thank you for participation to make the gem better! Very appreciated!

**Comment by sinankeskin** [comment]
Hi. I can confirm that, message disappeared now.

Thank you for the great tool and amazing effort.

**Comment by djezzzl** [comment]
Great, thank you!

P.S. If you have any ideas/requests what else we can potentially check, I'd be happy to implement. 

Have a great day 👍
