### ISSUE TITLE
 Check for IDs and foreign keys using Integers instead of BigInt

### ISSUE THREAD

**Issue by fidalgo** [djezzzl/database_consistency#50]
As reported on a similar project:
https://github.com/gregnavis/active_record_doctor/issues/38

Given no one is immune to it https://m.signalvnoise.com/update-on-basecamp-3-being-stuck-in-read-only-as-of-nov-8-922am-cst/

and there's a lot of people using Rails from prior this https://github.com/rails/rails/pull/26266

So a check for it would be awesome!

**Comment by djezzzl** [comment]
Hi @fidalgo , thank you for your suggestion! 

We will definitely add it 👍

**Comment by djezzzl** [comment]
Hey, keeping you posted. https://github.com/djezzzl/database_consistency#primarykeytypechecker was just released with version `0.8.0`. Soon I'll add `ForeignKeyTypeChecker`.

**Comment by fidalgo** [comment]
thanks @djezzzl Amazing work, I will test it soon.
Also you've messed with the links here: https://github.com/djezzzl/database_consistency/pull/51/files#diff-04c6e90faac2675aa89e2176d2eec7d8R153
(both links to rails PR, when I think you should meant for https://m.signalvnoise.com/update-on-basecamp-3-being-stuck-in-read-only-as-of-nov-8-922am-cst/)

**Comment by djezzzl** [comment]
Yeah, thank you! I'll update it.

**Comment by djezzzl** [comment]
Hi @fidalgo, letting you know that I finally found some time (just excuses 😄 ) and implemented [ForeignKeyTypeChecker](https://github.com/djezzzl/database_consistency#foreignkeytypechecker).

As [PrimaryKeyTypeChecker](https://github.com/djezzzl/database_consistency#primarykeytypechecker) was already shipped many months ago, I believe we can close the issue. Please let me know if you have any ideas or have any issues 👍
