### ISSUE TITLE
Ignore Rails 6 warnings concerning ActionText and ActiveStorage models

### ISSUE THREAD

**Issue by goulvench** [djezzzl/database_consistency#52]
Hi, thanks for the useful gem!

I'm using Rails 6.0.2.1 with ActiveStorage and ActionText (I don't think I did anything special during my Rails install), yet database_consistency reports the following failures:

```
fail ActionText::RichText name column is required in the database but do not have presence validator
fail ActiveStorage::Attachment name column is required in the database but do not have presence validator
fail ActiveStorage::Blob key column is required in the database but do not have presence validator
fail ActiveStorage::Blob filename column is required in the database but do not have presence validator
fail ActiveStorage::Blob byte_size column is required in the database but do not have presence validator
fail ActiveStorage::Blob checksum column is required in the database but do not have presence validator
```

I ignored them by adding the following code to my .database_consistency.yml but I'm thinking that this could be added to a generator, or to the [Rails6 example](https://github.com/djezzzl/database_consistency/blob/master/rails6-example/.database_consistency.yml).

```
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
```

Let me know what you think would be best, I could try my hand at a PR if needed.

**Comment by djezzzl** [comment]
Hey, thank you for your kind words! Very glad the gem helps you 👍 

I think, we could have a setup script for the gem which just creates a basic configuration example with some pre-defined rules which may be edited on demand. 

Do you want to do that? If you don't have time, we can just add these configurations to an example as you suggested 👍 (you may also do that simple PR if you want, just let me know)

**Comment by djezzzl** [comment]
I'll close issue for now. We can continue discussion, of course 👍

**Comment by goulvench** [comment]
I've looked at adding a generator but nothing worked (then got side-tracked by other work). I've added a PR to add the settings to the example, for starters.

I'm looking at generators again, will send a PR if I find a way to make this work.
