### ISSUE TITLE
A way to exclude some fails on per-file basis?

### ISSUE THREAD

**Issue by dmytro-savochkin** [djezzzl/database_consistency#53]
Hello.
This is a nice gem and I'd like to try it in our project. However as it turned out we have quite many fails. Because of that we would like to have some way to mark them all excluded (similar to rubocop_todo.yml) and integrate this gem into our CI tool so we can fix them later one by one. This approach would ensure we don't introduce new fails while we are fixing the old ones. Unfortunately I can't see a way to exclude fails on per-file (per-model) basis right now. Maybe there are plans for this? :)

**Comment by djezzzl** [comment]
Hey, thank you for using it. 

Yes, there is way to configure it, you probably skip. Please have a read https://github.com/djezzzl/database_consistency#configuration. There are examples inside how to disable the whole model. 

If it doesn't help, please let me know and reopen the issue. For now, I close it.

**Comment by dmytro-savochkin** [comment]
Wow, missed it for some reason, thanks!

**Comment by djezzzl** [comment]
No problem! Have a great day!
