### ISSUE TITLE
Consider adding Numericality validator to NullConstraintChecker?

### ISSUE THREAD

**Issue by bobmaerten** [djezzzl/database_consistency#56]
Hi, and first of all thanks for this gem, we had tremendous amount of alerts fixed in our codebase.

According to [Rails documentation](https://guides.rubyonrails.org/active_record_validations.html#numericality), `numericality` does not allow nil values by default. In our validations, we omit the presence validator in favor of numericality but `database_consitency` report a missing presence if these cases.

I don't really know if it would take much time to dig the source code of this gem and come with a PR on this matter. What do you think?

**Comment by djezzzl** [comment]
Hi @bobmaerten, thank you for your kind words! I'm glad that gem is useful for you! 

That should very simple, you just need to add one more rule to that checker to see if there is any `NumericalValidator` on that column with `allow_nil: false`. 

Let me know if you don't have time for that, so I can do it myself 👍

**Comment by bobmaerten** [comment]
Glad to contribute to a tool we use.

**Comment by djezzzl** [comment]
Hey, thank you for your contribution! Please try out version `0.8.2` and check if it works for you as expected 👍

**Comment by bobmaerten** [comment]
Removed all `presence` + `numericality` patterns upon our models with success. Thanks again for this precious gem.
