### ISSUE TITLE
false positive for validation with condition

### ISSUE THREAD

**Issue by yao0204** [djezzzl/database_consistency#58]
Hi, it seems it will check the validation even though we have a condition 
Like this 

```validates :code, presence: true, on: :update```

It fails even though it validates only on update. 

Is it a known/wanted behavior? 

Thanks

**Comment by djezzzl** [comment]
Hey, thank you for bringing this up! 

I agree with you that we shouldn't require a `non-null` constraint for such cases. Although, I'm not sure which context we can ignore and which not. I didn't use them much. What are default context which covers all CRUD ActiveRecord persistence actions? Probably, just `update` and `save`? 

BTW, Do you want to contribute to the gem or you want me to implement the fix?

**Comment by djezzzl** [comment]
Hey, could you please try version 0.8.3 and let me know if it doesn't work for you.

Thank you again!
