### ISSUE TITLE
False positive for unique index

### ISSUE THREAD

**Issue by yao0204** [djezzzl/database_consistency#59]
Hi, we recently encountered this problem: 

in the code we have the following, and package_type is a relation 
```
validates :zipcode, uniqueness: { scope: [:package_type] }
```
And in the database, we have the unique index 
`index_blacklist_zipcodes_on_package_type_id_and_zipcode  (package_type_id,zipcode) UNIQUE`

But the gem does not recognize it, because in the validation, we didn't write `package_type_id` 

Do you think this can be something easy to fix? 

Thanks a lot

**Comment by djezzzl** [comment]
Hi, thank you for reaching out with the issue! 

I think you can fix it by changing 
`validates :zipcode, uniqueness: { scope: [:package_type] }` to 
`validates :zipcode, uniqueness: { scope: [:package_type_id] }`

According to [the Rails docs](https://guides.rubyonrails.org/active_record_validations.html#uniqueness) `scope` should be an attribute. 

Please try it out and let me know if it doesn't help. 

Please share your thoughts if you still want to continue with `scope: :package_type` instead, so we can change adopt the gem to consider relations too.

For now, I close the issue but feel free to reopen it anytime 👍

**Comment by yao0204** [comment]
Hi, 
Indeed changing it to `_id` does work. 
But it would be nice if we could support both. I feel it's a bit redundant to write out the id when it's a relation. 
Thanks a lot

**Comment by djezzzl** [comment]
Hey, could you please try version `0.8.3` and let me know if it doesn't work for you.
