### ISSUE TITLE
False positive on array length

### ISSUE THREAD

**Issue by Ayliane** [djezzzl/database_consistency#61]
Hello,

So I have this model with an array field like this :

`t.string "content", limit: 255, array: true`

It causes the length validator to raise, but it's not correct, since the database validation is that every element of that array isn't bigger than 255, not the array itself. Is this behavior wanted ? I think that the only way to validate this is to have a custom validator, and i'm not sure that it would prevent database_consistency to complain ?

**Comment by djezzzl** [comment]
Hi @Ayliane, 

Thank you for pointing this out! Could you please try version `0.8.4` and see if it works fine for you now?

Feel free to re-open the issue if it still fails when it shouldn't.
