### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by djezzzl** [djezzzl/database_consistency#7]
Hi guys, thank you for using this gem. I hope it helps you 👍 

The purpose of this topic is to discuss what should be added next? 

Possible features (random order):
- [ ] more detailed output in `DEBUG` mode
- [ ] generate migrations
- [ ] provide support for different ORMs 
- [ ] accept list of files as arguments to check only them
- [ ] support `through` associations for `MissingIndexChecker`
- [ ] distinguish between hot/cold issues (i.e. many associations points on FK without index)

*Any requests are welcome to be discussed!*

**Comment by pancutan** [comment]
Thanks buddy, it's a useful and handy gem.

My only contribution to version 0.2.5

I take note that the gem alerts in legacy schemas, if the model uses another primary id than the default one provided by ActiveRecord, :id

In my case, I have a primary key declared as

```
class Carrera < ApplicationRecord
  self.primary_key = 'codigocarrera' 
```

The message is
```fail column id of table carreras of model Carrera is required but do not have presence validator```

However, the message is still useful, because suggest to add a validation like
```validates_presence_of :codigocarrera```

After that, warning message disappears.

Thanks for you great job

**Comment by djezzzl** [comment]
Hi @pancutan, thanks for your warm words.
It's strange because we have this check: https://github.com/djezzzl/database_consistency/blob/master/lib/database_consistency/column_verifiers/presence_missing_verifier.rb#L18. 

Mostly, IDs should be generated by the database so we can avoid using `presence` validators on them. But in some cases application generates IDs, so it's better to have the validation. 

I'll test your issue later or you can try to investigate it 👍 

Anyway, thank you!

**Comment by palkan** [comment]
Hey @djezzzl!

Gave this gem another try (btw, in Rails 6 - works fine 👍).

Found a couple of problems:

- Some models could have no DB tables.

Sounds strange, but that could happen, for example, if you have a gem with some _optinal_ models.
In my case that was `pg_search` gem and its `PgSearch::Document` model which we don't use.

To avoid the failure I marked it as abstract class (i.e. `PgSearch::Document.abstract_class = true`).

It would be great to handle missing table exception and print a warning (not a failure).

- Some models are out of the developer control.

I have the following lines in my output:

```
fail RailsEventStoreActiveRecord::Event event_type column is required in the database but do not have presence validator
fail RailsEventStoreActiveRecord::Event data column is required in the database but do not have presence validator
fail RailsEventStoreActiveRecord::EventInStream stream column is required in the database but do not have presence validator
validator
fail ActiveStorage::Blob key column is required in the database but do not have presence validator
fail ActiveStorage::Blob filename column is required in the database but do not have presence validator
fail ActiveStorage::Blob byte_size column is required in the database but do not have presence validator
fail ActiveStorage::Attachment name column is required in the database but do not have presence validator
```

That's bad but that's not my responsibility.
Possible solution is to add a blacklist of models/namespaces. For example:

```yml
ignore:
 - "ActiveStorage::*"
 - "RailsEventStore::*"
```

- Compound indexes / polymorphic associations seem not to be supported

I have the following:

```
fail Home chat associated model should have proper index in the database
```

But in the model I have `has_one :chat, as: :chattable` and and index for `[:chattable_type, :chattable_id]`.


Btw, it would be helpful to get some more information about the failure: tbh, `should have proper index in the database` doesn't help a lot. For example, showing a list of the table indexes could be helpful.

**Comment by palkan** [comment]
Also, a feature request: `ColumnLengthChecker`.

A typical situation is when you use `string` type in Rails migration, which is transformed into `varchar(255)` (for Postgres) and thus you need a `length: {maximum: 255}` validation (to avoid DB-level exceptions).

**Comment by djezzzl** [comment]
Hey @palkan, some of your requests are resolved in `0.6.8` version, to specify:
- Now you can disable any model and there will be no error like previously (even if it's not a real model at all). 
- Compound indexes / polymorphic associations are supported not for `MissingIndexChecker`

Additional features:
- Colored output

Detailed output in `DEBUG` mode and `ColumnLengthChecker` will be addressed soon 👍

**Comment by AlexeyMatskevich** [comment]
Hello, how about adding support [citext](https://www.postgresql.org/docs/9.1/citext.html)? The gem is currently checking for availability lower(attribute) index, but use this index have some problem in rails, `citext` more comfortable solution to the problem case insensitive indexes.

**Comment by djezzzl** [comment]
Hey @AlexeyMatskevich , could you please help me to understand where you suggest to support it? For what kind of checkers? Where do you have issues right now?
