### ISSUE TITLE
UniqueIndexChecker

### ISSUE THREAD

**Issue by Berardpi** [djezzzl/database_consistency#77]
Hi @djezzzl!
Thx for the gem

I was wondering if it would be possible to add the inverse of MissingUniqueIndexChecker, i.e. a way to detect unique index constraint which are present in the schema but missing in the model. Is this something that can be added?

I can look into it and work on a PR if that's something you'd be willing to merge, but I'd appreciate some pointers.

Thanks!

**Comment by djezzzl** [comment]
Hey @Berardpi , I'd very welcome such feature. Feel free to implement it and ask for any help you need 👍

**Comment by Berardpi** [comment]
Thanks @djezzzl, I've submitted #78. Feel free to request changes!

**Comment by djezzzl** [comment]
Thank you for the PR! I'll have a look ASAP. I'll close the issue so we can discuss everything in the PR from now.
