### ISSUE TITLE
`belongs_to ... optional: false` with no `NOT NULL` column is not detected

### ISSUE THREAD

**Issue by pirj** [djezzzl/database_consistency#90]
Hey @djezzzl ! Me again :smile: 

Database consistency is missing (unless I'm missing something among a ton of things that it does detect) if an FK column is not marked as `null: false` (NOT NULL) in the DB schema, while it's `belongs_to` without `optional: false`.
`optional: true` became the default in Rails 4.2 if I'm not mistaken.

```ruby
# app/models/books.rb
class Books < ApplicationRecord
  belongs_to :user
end
```
```ruby
# db/schema.rb
  create_table "books", force: :cascade do |t|
    t.bigint "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_books_on_user_id"
  end

...

  add_foreign_key "books", "users"
```

```
# INSERT books (created_at, updated_at) values ('2021-01-01', '2021-01-01');
INSERT 0 1
Time: 4.294 ms
# SELECT * from books;
-[ RECORD 1 ]------------+--------------------
id                       | 1
user_id                  | [NULL]
created_at               | 2021-01-01 00:00:00
updated_at               | 2021-01-01 00:00:00
```
:boom:

I'll be happy to contribute such a check.

**Comment by djezzzl** [comment]
Hello @pirj,

Glad to hear you! You're right, we don't have such checker yet and I believe it would be amazing to have one. 

> I'll be happy to contribute such a check.

Could you please do it then? I'd be happy to help if you would need any 👍
