### ISSUE TITLE
false MissingIndexChecker report on double column unique index with a through on join object.

### ISSUE THREAD

**Issue by yld** [djezzzl/database_consistency#93]
Sorry if i'm wrong but...

With the following models:

```ruby
class User
  has_many  :rules
end

class Thing
  has_many  :rules
  has_many :users, through: :rules
end

class Rule
 belong_to :user
 belong_to :thing
end
```

After adding a unique index on 2 columns
```ruby
add_index :rules, %i[user_id, thing_id], unique: true
```

Then i get:

`MissingIndexChecker fail Thing rules associated model should have proper index in the database
...
`

Running Postgresql EXPLAIN show the defined index is used as expected.

First i extracted the has_many through SQL:

```ruby
[5] pry(main)> Thing.last.users.to_sql
=> "SELECT \"users\".* FROM \"users\" INNER JOIN \"rules\" ON \"users\".\"id\" = \"rules\".\"user_id\" WHERE \"rules\".\"thing_id\" = 88611"
```

Then i checked that defined index were correctly used:

```sql
EXPLAIN SELECT users.* FROM users INNER JOIN rules ON users.id = rules.user_id WHERE rules.thing_id = 8861 ;
```

Which gave me the following result:
```
                                                                QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=0.70..1355.76 rows=1 width=362)
   ->  Index Only Scan using index_rules_on_user_id_and_thing_id on rules  (cost=0.41..1347.45 rows=1 width=8)
         Index Cond: (thing_id = 8861)
   ->  Index Scan using users_pkey on users  (cost=0.29..8.30 rows=1 width=362)
         Index Cond: (id = rules.user_id)
(5 rows)
```

Same problem occurs on polymorphic relationships backed by a unique index on the `_id` and `_type` columns.

**Comment by djezzzl** [comment]
So far, I can't understand why that index is being used for such a query. 

Official docs say: 
```
A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns, but the index is most efficient when there are constraints on the leading (leftmost) columns.
```
from https://www.postgresql.org/docs/9.6/indexes-multicolumn.html. 

Could you please share the entire `/d rules` from your `psql` console?

P.S. `%i[user_id, thing_id],` has a typo as "comma" is redundant but I think your shared that just for an example.

**Comment by djezzzl** [comment]
Hey @yld, I need slightly more time with this issue as I can't so far understand why it's working like that. I'll have more spare time next week and continue my research on that.

**Comment by yld** [comment]
Any update?

**Comment by djezzzl** [comment]
Hello,

I’m so sorry it’s taking so long on this one. Unfortunately, I was very
busy with something else. Now, I’m sick.

I’ll do my best to get back to it once I recover.

Вт, 11 янв. 2022 г. в 13:23, yld ***@***.***>:

**Comment by djezzzl** [comment]
Hi @yld ,

Going from top to the bottom with latest version of the gem in your example:
```
MissingIndexChecker fail SecondThing second_rules associated model should have proper index in the database
```

Is correct, as you don't have index in `SecondRule` starting with `second_thing_id`.

The explain:
```
 second_thing.second_rules.explain
  SecondRule Load (0.7ms)  SELECT "second_rules".* FROM "second_rules" WHERE "second_rules"."second_thing_id" = $1  [["second_thing_id", 1]]
 => 
EXPLAIN for: SELECT "second_rules".* FROM "second_rules" WHERE "second_rules"."second_thing_id" = $1 [["second_thing_id", 1]]
                          QUERY PLAN
--------------------------------------------------------------
 Seq Scan on second_rules  (cost=0.00..21.62 rows=1 width=40)
   Filter: (second_thing_id = '1'::bigint)
(2 rows)
```

After adding an index it becomes correct:
```
 second_thing.second_rules.explain
  SecondRule Load (0.7ms)  SELECT "second_rules".* FROM "second_rules" WHERE "second_rules"."second_thing_id" = $1  [["second_thing_id", 1]]
 => 
EXPLAIN for: SELECT "second_rules".* FROM "second_rules" WHERE "second_rules"."second_thing_id" = $1 [["second_thing_id", 1]]
                                              QUERY PLAN
------------------------------------------------------------------------------------------------------
 Index Scan using second_rules_second_thing_id_idx on second_rules  (cost=0.28..8.29 rows=1 width=40)
   Index Cond: (second_thing_id = '1'::bigint)
(2 rows)
```

**Comment by djezzzl** [comment]
This:
```
MissingIndexChecker fail SecondGroup subscriptions associated model should have proper index in the database
```
Is wrong because your association definition was wrong:

it should be `second_subscriptions` not `subscriptions` as `Subscription` has no polymorphic `second_subscriber`
```
class SecondGroup < ApplicationRecord
  has_many :second_subscriptions, as: :second_subscriber
end
```

Once you finish the naming of an association, the check will work fine and disappear. Probably we could catch such issues somehow. Maybe by trying to call the association but we don't really do this, right now.

**Comment by djezzzl** [comment]
Same issue as above with `ThirdGroup.third_subscriptions`. Once you fix the association name, the gem work fine. BTW, with wrong/invalid name association doesn't work at all (just a reminder)

**Comment by djezzzl** [comment]
Same issue as above with `SecondUser.subscriptions` as it should be `SecondUser.second_subscriptions`.

**Comment by djezzzl** [comment]
```
MissingIndexChecker fail ThirdThing third_rules associated model should have proper index in the database
```
This issue by the gem is correct as you need to have a proper index for starting with `third_thing_id`. Without it, the index won't be used by the planner. You can check the explain output with/-out the index.

**Comment by djezzzl** [comment]
`ThirdUser.subscriptions` should be `ThirdUser.third_subscriptions`, so it's the same issue as some above.

**Comment by djezzzl** [comment]
```
thing.rules.explain
  Rule Load (0.5ms)  SELECT "rules".* FROM "rules" WHERE "rules"."thing_id" = $1  [["thing_id", 1]]
 => 
EXPLAIN for: SELECT "rules".* FROM "rules" WHERE "rules"."thing_id" = $1 [["thing_id", 1]]
                      QUERY PLAN
-------------------------------------------------------
 Seq Scan on rules  (cost=0.00..21.50 rows=1 width=40)
   Filter: (thing_id = '1'::bigint)
(2 rows)

```

`Thing.rules` require an index starting from `thing_id` too. Otherwise, it isn't being used efficiently enough. So the gem is correct here too.

**Comment by djezzzl** [comment]
Sorry for taking so long, I've investigated all of the issues you mentioned and so far gem is correct.

Please, be aware, that sometimes, PostgreSQL planners may behave differently because:
- the table wasn't yet analyzed; (`ANALYZE users;`) 
- the table was analyzed and it may have the amount of the data that makes index usage irrelevant.  That's why it's better to fill the table with many rows before testing such.
- some other circumstances, i.e. plugins/custom planners/etc.

But gem follows correctly the general behavior of PostgreSQL that is being described in the official docs.

Please feel free to reopen the issue if needed.
