### ISSUE TITLE
enum + validation consistency check

### ISSUE THREAD

**Issue by mpapis** [djezzzl/database_consistency#98]
Hi :)

I've got quite few enum's in database and I've found few instances when the Rails enum was not set to include all DB enum values, this lead to reading the field as `nil` in case the value was missing in Rails enum.

Example:
 - schema: `t.column "type", "enum('STONE','TREE')", default: "STONE"`
 - model: `enum type: { "STONE" => "STONE", "TREES" => "TREES"], _prefix: :type`
 - validation: `validate :type, inclusion: { in:  %w[STONE TREES] }` - actually if enum is synced then this can be smaller list, but still it can include something invalid for DB - like `TREES` - note the extra `S`.
 
Do you think it can make place into the gem?

**Comment by pirj** [comment]
Filed https://github.com/djezzzl/database_consistency/issues/103 instead.

**Comment by mpapis** [comment]
@djezzzl please take care of it, I'm busy as usual ;)
@pirj thanks, that's another use case I haven't thought of

I would distinct at least those use cases:
- string enum in db & integer mapped enum in rails
- integer in db & string mapped enum in rails
- enum in db & string mapped enum in rails & different enums
- enum in db & validation in rails with more fields then in db enum

probably there might be a lot of fun finding all edge cases like defaults or constrains

**Comment by djezzzl** [comment]
Hi @mpapis,

Thank you for the suggestion! Sorry for taking it so long to be implemented. It was released in 1.6.0. Please let me know if that works for you.
